<?php
echo "<style>";
echo ".failure,.success {";
echo " width: 50%;";
echo " margin-top: 3em;";
echo " padding: 1em;";
echo " color: white;";
echo " text-align: center;";
echo " border-radius: 0em;";
echo " font-family: Courier New;";
echo " font-size: 2em;";
echo "}";
echo ".back {";
echo " text-decoration: none;";
echo " background-color: aquamarine;";
echo " padding: 0.5em;";
echo " color: #333333;";
echo " text-align: center;";
echo " border-radius: 1em;";
echo " font-family: Segoe UI Light;";
echo " font-size: 1.5em;";
echo " box-shadow: 1px 1px 1px 1px cadetblue;";
echo "}";
echo ".back:hover {";
echo " box-shadow: 0px 0px 0px 0px cadetblue;";
echo "}";
echo ".back:active {";
echo " box-shadow: 1px 1px 1px 1px cadetblue;";
echo "}";
echo "</style>";
?>